# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Automate One Thing
description: >- # this means to ignore newlines until "baseurl:"
  Automate One Thing (A1T) is a program to help F5 customers "get off the bench and into the 
  race" when it comes to automation. This repository contains examples, training material, 
  and workshop content.
baseurl: "/automate-one-thing" # the subpath of your site, e.g. /blog
url: "https://f5solutionsengineering.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
author: F5 Networks Solutions Engineering

collections:
  tools:
    output: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

titles_from_headings:
  enabled: true
  strip_title: true
  collections: false
