name: Jekyll
on: [push]

jobs:
  build:
    name: Jekyll
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: install prerequists
        run: gem install bundler jekyll html-proofer
      - name: test site
        run: |
          cd docs
          bundle exec jekyll build
          bundle exec htmlproofer ./_site --disable-external
