name: Jekyll
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Jekyll
    runs-on: ubuntu-latest
    container:
      image: jekyll/builder:3.8
      volumes:
        - /home/runner/work/:/svr/jekyll
    steps:
      - uses: actions/checkout@v2
      - name: Run in container
        run: |
          pwd
          ls -la
          chown -R jekyll /__w/automate-one-thing/automate-one-thing/docs
          cd /__w/automate-one-thing/automate-one-thing/docs
          pwd
          ls -la
          jekyll build
