name: Jekyll
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Jekyll
    # This job runs on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: install prerequists
        run: |
          cd docs
          pwd
          ls -la
          gem install bundler:2.1.4
          bundle install

      - name: test site
        run: |
          bundle exec jekyll build --source /home/runner/work/automate-one-thing/automate-one-thing/docs
          bundle exec htmlproofer ./_site --disable-external --url-ignore "/automate-one-thing/"
