name: SpellCheck
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: SpellCheck
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.2.0
