name: SpellCheck
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: SpellCheck
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: install pyspelling
        run: sudo pip install pyspelling
      - name: run pyspelling
        run: pyspelling -c spellcheck.yaml
